### ISSUE TITLE
Add option for Primary Nav

### ISSUE THREAD

**Issue by seothemes** [studiopress/genesis-simple-menus#6]
Recently needed to add the option for the Primary Nav as well as the Secondary Nav for a client site:

![image](https://user-images.githubusercontent.com/24793388/39125420-3cffee48-4742-11e8-985c-a2093ba608f6.png)

Thought I'd submit a PR - unless there is a reason why this is not enabled by default?

**Comment by dreamwhisper** [comment]
I can't recall if there was a specific reason not to do this, but we have had requests for it. I'm on board unless someone can think of a reason not to.

**Comment by dreamwhisper** [comment]
https://github.com/copyblogger/genesis-simple-menus/pull/7

**Comment by dreamwhisper** [comment]
The PR for this will need a refresh after the code standards release.

**Comment by nathanrice** [comment]
Fixed in #7
